# Generated by Django 6.0.4 on 2026-04-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование категории",
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование категории",
                    ),
                ),
                (
                    "slug_name",
                    models.SlugField(
                        help_text="Введите slug-имя категории",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug-имя категории",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение категории",
                        null=True,
                        upload_to="product/category_image",
                        verbose_name="Изображение категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование подкатегории",
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование подкатегории",
                    ),
                ),
                (
                    "slug_name",
                    models.SlugField(
                        help_text="Введите slug-имя подкатегории",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug-имя подкатегории",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение подкатегории",
                        null=True,
                        upload_to="product/subcategory_image",
                        verbose_name="Изображение подкатегории",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование товара",
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование товара",
                    ),
                ),
                (
                    "slug_name",
                    models.SlugField(
                        help_text="Введите slug-имя товара",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug-имя товара",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Введите цену товара", verbose_name="Цена товара"
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите 1 изображение товара",
                        null=True,
                        upload_to="product/product_image1",
                        verbose_name="Изображение товара 1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите 2 изображение товара",
                        null=True,
                        upload_to="product/product_image2",
                        verbose_name="Изображение товара 2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите 3 изображение товара",
                        null=True,
                        upload_to="product/product_image3",
                        verbose_name="Изображение товара 3",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.subcategory",
                        verbose_name="Подкатегория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
